-- ============================================================
-- PROCUREMENT MODULE SCHEMA (Phase 0)
-- Run this file in SQL Developer connected as QUOTEAPP user.
-- This is ADDITIVE — it does NOT modify existing tables destructively.
-- To undo, run schema_procurement_rollback.sql
-- ============================================================

-- ==========================
-- 1. RELAX USER ROLE CONSTRAINT
-- ==========================
ALTER TABLE QA_USERS DROP CONSTRAINT CHK_USERS_ROLE;
ALTER TABLE QA_USERS ADD CONSTRAINT CHK_USERS_ROLE
    CHECK (USER_ROLE IN ('sales', 'controller', 'procurement', 'admin'));

-- ==========================
-- 2. ADDITIVE COLUMNS ON QA_INVOICES (non-destructive)
-- ==========================
ALTER TABLE QA_INVOICES ADD (
    SOURCING_STATUS VARCHAR2(20) DEFAULT 'NONE',
    PR_COUNT        NUMBER(5,0)  DEFAULT 0
);

ALTER TABLE QA_INVOICES ADD CONSTRAINT CHK_INV_SOURCING
    CHECK (SOURCING_STATUS IN ('NONE','PENDING','PARTIAL','COMPLETE'));

-- ==========================
-- 3. SEQUENCES for human-friendly numbers
-- ==========================
CREATE SEQUENCE QA_PR_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE QA_RFQ_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- ==========================
-- 4. TABLE: VENDORS
-- ==========================
CREATE TABLE QA_VENDORS (
    VENDOR_ID       VARCHAR2(50)   NOT NULL,
    VENDOR_NAME     VARCHAR2(500)  NOT NULL,
    CONTACT_PERSON  VARCHAR2(255),
    CONTACT_EMAIL   VARCHAR2(255),
    CONTACT_PHONE   VARCHAR2(100),
    CATEGORY        VARCHAR2(100),
    STATUS          VARCHAR2(20)   DEFAULT 'active',
    RATING          NUMBER(3,1)    DEFAULT 0,
    PAYMENT_TERMS   VARCHAR2(100),
    LEAD_TIME_DAYS  NUMBER(5,0)    DEFAULT 0,
    ADDRESS         VARCHAR2(500),
    NOTES           VARCHAR2(4000),
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CREATED_BY      VARCHAR2(255),
    UPDATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_BY      VARCHAR2(255),
    CONSTRAINT PK_VENDORS PRIMARY KEY (VENDOR_ID),
    CONSTRAINT CHK_VENDOR_STATUS CHECK (STATUS IN ('active','inactive','suspended')),
    CONSTRAINT CHK_VENDOR_RATING CHECK (RATING BETWEEN 0 AND 5)
);

CREATE INDEX IDX_VENDOR_NAME     ON QA_VENDORS(VENDOR_NAME);
CREATE INDEX IDX_VENDOR_CATEGORY ON QA_VENDORS(CATEGORY);
CREATE INDEX IDX_VENDOR_STATUS   ON QA_VENDORS(STATUS);

-- ==========================
-- 5. TABLE: PURCHASE REQUISITIONS
-- ==========================
CREATE TABLE QA_PURCHASE_REQUISITIONS (
    PR_ID                VARCHAR2(50)   NOT NULL,
    PR_NUMBER            VARCHAR2(50),
    INVOICE_ID           VARCHAR2(50),
    QUOTE_LINE_MATCH_KEY VARCHAR2(200),
    ITEM_NAME            VARCHAR2(500),
    ITEM_DESCRIPTION     VARCHAR2(4000),
    QUANTITY             NUMBER(10,2)   DEFAULT 1,
    UOM                  VARCHAR2(20)   DEFAULT 'EA',
    NEEDED_BY            VARCHAR2(50),
    REASON               VARCHAR2(30)   DEFAULT 'CUSTOM_SOURCED',
    STATUS               VARCHAR2(20)   DEFAULT 'OPEN',
    PRIORITY             VARCHAR2(20)   DEFAULT 'normal',
    REQUESTED_BY         VARCHAR2(255),
    ASSIGNED_TO          VARCHAR2(255),
    CUSTOMER_NAME        VARCHAR2(500),
    NOTES                VARCHAR2(4000),
    CREATED_AT           TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT           TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_PR PRIMARY KEY (PR_ID),
    CONSTRAINT FK_PR_INVOICE FOREIGN KEY (INVOICE_ID)
        REFERENCES QA_INVOICES(INVOICE_ID) ON DELETE SET NULL,
    CONSTRAINT CHK_PR_REASON CHECK (REASON IN
        ('OUT_OF_STOCK','INSUFFICIENT','NOT_IN_INVENTORY','CUSTOM_SOURCED')),
    CONSTRAINT CHK_PR_STATUS CHECK (STATUS IN
        ('OPEN','IN_RFQ','AWARDED','FULFILLED','CANCELLED','REJECTED')),
    CONSTRAINT CHK_PR_PRIORITY CHECK (PRIORITY IN ('low','normal','high','urgent'))
);

CREATE INDEX IDX_PR_INVOICE   ON QA_PURCHASE_REQUISITIONS(INVOICE_ID);
CREATE INDEX IDX_PR_STATUS    ON QA_PURCHASE_REQUISITIONS(STATUS);
CREATE INDEX IDX_PR_ASSIGNED  ON QA_PURCHASE_REQUISITIONS(ASSIGNED_TO);
CREATE INDEX IDX_PR_CREATED   ON QA_PURCHASE_REQUISITIONS(CREATED_AT);

-- ==========================
-- 6. TABLE: RFQ HEADERS
-- ==========================
CREATE TABLE QA_RFQS (
    RFQ_ID               VARCHAR2(50)   NOT NULL,
    RFQ_NUMBER           VARCHAR2(50),
    TITLE                VARCHAR2(500),
    STATUS               VARCHAR2(30)   DEFAULT 'DRAFT',
    SUBMISSION_DEADLINE  VARCHAR2(50),
    DELIVERY_DEADLINE    VARCHAR2(50),
    AWARDED_VENDOR_ID    VARCHAR2(50),
    AWARDED_AT           TIMESTAMP,
    AWARDED_BY           VARCHAR2(255),
    TOTAL_AWARD_AMOUNT   NUMBER(15,4)   DEFAULT 0,
    CURRENCY             VARCHAR2(10)   DEFAULT 'GHS',
    NOTES                VARCHAR2(4000),
    CREATED_BY           VARCHAR2(255),
    CREATED_AT           TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT           TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_RFQ PRIMARY KEY (RFQ_ID),
    CONSTRAINT FK_RFQ_VENDOR FOREIGN KEY (AWARDED_VENDOR_ID)
        REFERENCES QA_VENDORS(VENDOR_ID) ON DELETE SET NULL,
    CONSTRAINT CHK_RFQ_STATUS CHECK (STATUS IN
        ('DRAFT','SENT','RECEIVING','COMPARING','PENDING_APPROVAL','AWARDED','CANCELLED','CLOSED'))
);

CREATE INDEX IDX_RFQ_STATUS    ON QA_RFQS(STATUS);
CREATE INDEX IDX_RFQ_VENDOR    ON QA_RFQS(AWARDED_VENDOR_ID);
CREATE INDEX IDX_RFQ_CREATED   ON QA_RFQS(CREATED_AT);

-- ==========================
-- 7. TABLE: RFQ LINE ITEMS (M:N between RFQs and PRs)
-- ==========================
CREATE TABLE QA_RFQ_LINE_ITEMS (
    RFQ_LINE_ID  NUMBER         GENERATED ALWAYS AS IDENTITY,
    RFQ_ID       VARCHAR2(50)   NOT NULL,
    PR_ID        VARCHAR2(50)   NOT NULL,
    ITEM_NAME    VARCHAR2(500),
    QUANTITY     NUMBER(10,2)   DEFAULT 1,
    SORT_ORDER   NUMBER(5,0)    DEFAULT 0,
    CONSTRAINT PK_RFQ_LI PRIMARY KEY (RFQ_LINE_ID),
    CONSTRAINT FK_RFQ_LI_RFQ FOREIGN KEY (RFQ_ID)
        REFERENCES QA_RFQS(RFQ_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RFQ_LI_PR FOREIGN KEY (PR_ID)
        REFERENCES QA_PURCHASE_REQUISITIONS(PR_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_RFQ_LI_RFQ ON QA_RFQ_LINE_ITEMS(RFQ_ID);
CREATE INDEX IDX_RFQ_LI_PR  ON QA_RFQ_LINE_ITEMS(PR_ID);

-- ==========================
-- 8. TABLE: RFQ VENDORS (vendors invited per RFQ)
-- ==========================
CREATE TABLE QA_RFQ_VENDORS (
    RFQ_VENDOR_ID     NUMBER         GENERATED ALWAYS AS IDENTITY,
    RFQ_ID            VARCHAR2(50)   NOT NULL,
    VENDOR_ID         VARCHAR2(50)   NOT NULL,
    EMAIL_SENT_AT     TIMESTAMP,
    EMAIL_MESSAGE_ID  VARCHAR2(500),
    RESPONSE_STATUS   VARCHAR2(20)   DEFAULT 'PENDING',
    CONSTRAINT PK_RFQ_VENDORS PRIMARY KEY (RFQ_VENDOR_ID),
    CONSTRAINT FK_RV_RFQ FOREIGN KEY (RFQ_ID)
        REFERENCES QA_RFQS(RFQ_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RV_VENDOR FOREIGN KEY (VENDOR_ID)
        REFERENCES QA_VENDORS(VENDOR_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_RV_STATUS CHECK (RESPONSE_STATUS IN
        ('PENDING','RESPONDED','DECLINED','NO_RESPONSE')),
    CONSTRAINT UQ_RFQ_VENDOR UNIQUE (RFQ_ID, VENDOR_ID)
);

CREATE INDEX IDX_RV_RFQ    ON QA_RFQ_VENDORS(RFQ_ID);
CREATE INDEX IDX_RV_VENDOR ON QA_RFQ_VENDORS(VENDOR_ID);

-- ==========================
-- 9. TABLE: RFQ RESPONSES (manually entered by procurement)
-- ==========================
CREATE TABLE QA_RFQ_RESPONSES (
    RESPONSE_ID     NUMBER         GENERATED ALWAYS AS IDENTITY,
    RFQ_ID          VARCHAR2(50)   NOT NULL,
    VENDOR_ID       VARCHAR2(50)   NOT NULL,
    PR_ID           VARCHAR2(50)   NOT NULL,
    UNIT_COST       NUMBER(15,4)   DEFAULT 0,
    QUANTITY        NUMBER(10,2)   DEFAULT 1,
    TOTAL_COST      NUMBER(15,4)   DEFAULT 0,
    CURRENCY        VARCHAR2(10)   DEFAULT 'GHS',
    LEAD_TIME_DAYS  NUMBER(5,0)    DEFAULT 0,
    FREIGHT         NUMBER(15,4)   DEFAULT 0,
    DELIVERY_TERMS  VARCHAR2(100),
    PAYMENT_TERMS   VARCHAR2(100),
    VALIDITY_DAYS   NUMBER(5,0)    DEFAULT 30,
    NOTES           VARCHAR2(4000),
    IS_WINNER       NUMBER(1)      DEFAULT 0,
    LOGGED_BY       VARCHAR2(255),
    LOGGED_AT       TIMESTAMP      DEFAULT SYSTIMESTAMP,
    RECEIVED_DATE   VARCHAR2(50),
    CONSTRAINT PK_RFQ_RESP PRIMARY KEY (RESPONSE_ID),
    CONSTRAINT FK_RR_RFQ FOREIGN KEY (RFQ_ID)
        REFERENCES QA_RFQS(RFQ_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RR_VENDOR FOREIGN KEY (VENDOR_ID)
        REFERENCES QA_VENDORS(VENDOR_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RR_PR FOREIGN KEY (PR_ID)
        REFERENCES QA_PURCHASE_REQUISITIONS(PR_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_RR_WINNER CHECK (IS_WINNER IN (0,1))
);

CREATE INDEX IDX_RR_RFQ    ON QA_RFQ_RESPONSES(RFQ_ID);
CREATE INDEX IDX_RR_VENDOR ON QA_RFQ_RESPONSES(VENDOR_ID);
CREATE INDEX IDX_RR_PR     ON QA_RFQ_RESPONSES(PR_ID);
CREATE INDEX IDX_RR_WINNER ON QA_RFQ_RESPONSES(IS_WINNER);

-- ==========================
-- 10. TABLE: PROCUREMENT EVENTS (append-only audit log)
-- ==========================
CREATE TABLE QA_PROCUREMENT_EVENTS (
    EVENT_ID    NUMBER         GENERATED ALWAYS AS IDENTITY,
    EVENT_TIME  TIMESTAMP      DEFAULT SYSTIMESTAMP,
    EVENT_TYPE  VARCHAR2(50)   NOT NULL,
    ENTITY_TYPE VARCHAR2(20)   NOT NULL,
    ENTITY_ID   VARCHAR2(50),
    ACTOR       VARCHAR2(255),
    PAYLOAD     CLOB,
    CONSTRAINT PK_PROC_EVENTS PRIMARY KEY (EVENT_ID),
    CONSTRAINT CHK_PE_ENTITY CHECK (ENTITY_TYPE IN
        ('PR','RFQ','VENDOR','RESPONSE','SETTING'))
);

CREATE INDEX IDX_PE_TYPE   ON QA_PROCUREMENT_EVENTS(EVENT_TYPE);
CREATE INDEX IDX_PE_ENTITY ON QA_PROCUREMENT_EVENTS(ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IDX_PE_TIME   ON QA_PROCUREMENT_EVENTS(EVENT_TIME);

-- ==========================
-- 11. TABLE: PROCUREMENT SETTINGS
-- ==========================
CREATE TABLE QA_PROCUREMENT_SETTINGS (
    SETTING_KEY VARCHAR2(50)   NOT NULL,
    SETTING_VAL CLOB,
    UPDATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_BY  VARCHAR2(255),
    CONSTRAINT PK_PROC_SETTINGS PRIMARY KEY (SETTING_KEY)
);

-- Seed defaults (approval threshold OFF by default)
INSERT INTO QA_PROCUREMENT_SETTINGS (SETTING_KEY, SETTING_VAL) VALUES ('highValueThreshold',     '0');
INSERT INTO QA_PROCUREMENT_SETTINGS (SETTING_KEY, SETTING_VAL) VALUES ('minVendorsPerRFQ',       '3');
INSERT INTO QA_PROCUREMENT_SETTINGS (SETTING_KEY, SETTING_VAL) VALUES ('defaultRFQDeadlineDays', '7');
INSERT INTO QA_PROCUREMENT_SETTINGS (SETTING_KEY, SETTING_VAL) VALUES ('enableProcurementModule','true');
INSERT INTO QA_PROCUREMENT_SETTINGS (SETTING_KEY, SETTING_VAL) VALUES ('defaultCurrency',        'GHS');

COMMIT;

-- Verification: expect 8 new procurement tables + 2 sequences
SELECT TABLE_NAME FROM USER_TABLES
WHERE TABLE_NAME IN (
    'QA_VENDORS','QA_PURCHASE_REQUISITIONS','QA_RFQS','QA_RFQ_LINE_ITEMS',
    'QA_RFQ_VENDORS','QA_RFQ_RESPONSES','QA_PROCUREMENT_EVENTS','QA_PROCUREMENT_SETTINGS'
)
ORDER BY TABLE_NAME;

SELECT SEQUENCE_NAME FROM USER_SEQUENCES
WHERE SEQUENCE_NAME IN ('QA_PR_SEQ','QA_RFQ_SEQ')
ORDER BY SEQUENCE_NAME;
