-- ============================================================
-- STEP 2: Run this file SECOND, connected as QUOTEAPP user
-- In SQL Developer: Connect as user=quoteapp, password=QuoteApp2024#Secure!
-- Service: XEPDB1, Port: 1521
-- Run the ENTIRE script at once.
-- ============================================================

-- ==========================
-- TABLE 1: USERS
-- ==========================
CREATE TABLE QA_USERS (
    USER_EMAIL    VARCHAR2(255)  NOT NULL,
    USER_ROLE     VARCHAR2(20)   DEFAULT 'sales'  NOT NULL,
    USER_NAME     VARCHAR2(255),
    USER_STATUS   VARCHAR2(20)   DEFAULT 'active',
    CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_EMAIL),
    CONSTRAINT CHK_USERS_ROLE CHECK (USER_ROLE IN ('sales', 'controller'))
);

-- ==========================
-- TABLE 2: OTPS
-- ==========================
CREATE TABLE QA_OTPS (
    OTP_EMAIL     VARCHAR2(255)  NOT NULL,
    OTP_CODE      NUMBER(6)      NOT NULL,
    CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP,
    EXPIRES_AT    TIMESTAMP      DEFAULT (SYSTIMESTAMP + INTERVAL '10' MINUTE),
    CONSTRAINT PK_OTPS PRIMARY KEY (OTP_EMAIL)
);

-- ==========================
-- TABLE 3: CUSTOMERS
-- ==========================
CREATE TABLE QA_CUSTOMERS (
    CUSTOMER_ID       VARCHAR2(50)   NOT NULL,
    CUSTOMER_NAME     VARCHAR2(500)  NOT NULL,
    CONTACT_PERSON    VARCHAR2(255),
    CONTACT_EMAIL     VARCHAR2(255),
    LOCATION          VARCHAR2(255),
    PO_BOX            VARCHAR2(100),
    REGION            VARCHAR2(100),
    ADDRESS           VARCHAR2(500),
    NOTES             VARCHAR2(4000),
    CUSTOMER_SINCE    VARCHAR2(50),
    CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
);

CREATE INDEX IDX_CUST_NAME   ON QA_CUSTOMERS(CUSTOMER_NAME);
CREATE INDEX IDX_CUST_EMAIL  ON QA_CUSTOMERS(CONTACT_EMAIL);
CREATE INDEX IDX_CUST_REGION ON QA_CUSTOMERS(REGION);

-- ==========================
-- TABLE 4: INVENTORY
-- ==========================
CREATE TABLE QA_INVENTORY (
    SKU                VARCHAR2(100)  NOT NULL,
    ITEM_NAME          VARCHAR2(500)  NOT NULL,
    VENDOR             VARCHAR2(255),
    STOCK              NUMBER(10,0)   DEFAULT 0,
    PRICE              NUMBER(15,4)   DEFAULT 0,
    RESTOCK_LIMIT      NUMBER(10,0)   DEFAULT 0,
    CURRENCY           VARCHAR2(10)   DEFAULT 'GHS',
    UNIT_COST          NUMBER(15,4),
    WEIGHT_KG          NUMBER(10,4),
    DIM_LENGTH         NUMBER(10,4),
    DIM_WIDTH          NUMBER(10,4),
    DIM_HEIGHT         NUMBER(10,4),
    FREIGHT_PER_UNIT   NUMBER(15,4)   DEFAULT 0,
    DUTY_PER_UNIT      NUMBER(15,4)   DEFAULT 0,
    INSURANCE_PER_UNIT NUMBER(15,4)   DEFAULT 0,
    PACKAGING_PER_UNIT NUMBER(15,4)   DEFAULT 0,
    OTHER_PER_UNIT     NUMBER(15,4)   DEFAULT 0,
    MARKUP_OVERRIDE    NUMBER(10,4),
    PRICING_TIER       VARCHAR2(20)   DEFAULT 'standard',
    UPDATED_AT         TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_BY         VARCHAR2(255),
    CONSTRAINT PK_INVENTORY PRIMARY KEY (SKU)
);

CREATE INDEX IDX_INV_NAME   ON QA_INVENTORY(ITEM_NAME);
CREATE INDEX IDX_INV_VENDOR ON QA_INVENTORY(VENDOR);
CREATE INDEX IDX_INV_STOCK  ON QA_INVENTORY(STOCK);

-- ==========================
-- SEQUENCE: Invoice Auto-Number
-- ==========================
CREATE SEQUENCE QA_INVOICE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- ==========================
-- TABLE 5: INVOICES
-- ==========================
CREATE TABLE QA_INVOICES (
    INVOICE_ID           VARCHAR2(50)   NOT NULL,
    APPROVED_INVOICE_ID  VARCHAR2(50),
    SALESPERSON_ID       VARCHAR2(255),
    CREATED_BY           VARCHAR2(255),
    CUSTOMER_ID          VARCHAR2(50),
    CUSTOMER_NAME        VARCHAR2(500),
    INVOICE_DATE         VARCHAR2(20),
    CURRENCY             VARCHAR2(10)   DEFAULT 'GHS',
    EXCHANGE_RATE        NUMBER(15,6)   DEFAULT 1,
    SUBTOTAL             NUMBER(15,4)   DEFAULT 0,
    TOTAL                NUMBER(15,4)   DEFAULT 0,
    TAXES                NUMBER(15,4)   DEFAULT 0,
    TAX_BREAKDOWN        CLOB,
    STATUS               VARCHAR2(50)   DEFAULT 'Pending Pricing',
    SUBMITTED_AT         TIMESTAMP,
    APPROVED_AT          TIMESTAMP,
    APPROVED_BY          VARCHAR2(255),
    REJECTED_AT          TIMESTAMP,
    REJECTED_BY          VARCHAR2(255),
    REJECTION_REASON     VARCHAR2(4000),
    CUSTOMER_ACTION_AT   TIMESTAMP,
    SIGNATURE_DATA       CLOB,
    AMOUNT_PAID          NUMBER(15,4)   DEFAULT 0,
    BALANCE_DUE          NUMBER(15,4)   DEFAULT 0,
    CONVERTED_FROM_QUOTE VARCHAR2(50),
    CONVERSION_DATE      TIMESTAMP,
    CREATED_AT           TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT           TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_INVOICES PRIMARY KEY (INVOICE_ID),
    CONSTRAINT FK_INV_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES QA_CUSTOMERS(CUSTOMER_ID)
);

CREATE INDEX IDX_INV_CUSTOMER   ON QA_INVOICES(CUSTOMER_ID);
CREATE INDEX IDX_INV_STATUS     ON QA_INVOICES(STATUS);
CREATE INDEX IDX_INV_DATE       ON QA_INVOICES(INVOICE_DATE);
CREATE INDEX IDX_INV_CREATED_BY ON QA_INVOICES(CREATED_BY);

-- ==========================
-- TABLE 6: INVOICE LINE ITEMS
-- ==========================
CREATE TABLE QA_INVOICE_LINE_ITEMS (
    LINE_ID    NUMBER         GENERATED ALWAYS AS IDENTITY,
    INVOICE_ID VARCHAR2(50)   NOT NULL,
    SKU        VARCHAR2(100),
    ITEM_NAME  VARCHAR2(500),
    QUANTITY   NUMBER(10,2)   DEFAULT 1,
    UNIT_PRICE NUMBER(15,4)   DEFAULT 0,
    LINE_TOTAL NUMBER(15,4)   DEFAULT 0,
    SORT_ORDER NUMBER(5,0)    DEFAULT 0,
    CONSTRAINT PK_INV_LINE_ITEMS PRIMARY KEY (LINE_ID),
    CONSTRAINT FK_LI_INVOICE FOREIGN KEY (INVOICE_ID)
        REFERENCES QA_INVOICES(INVOICE_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_LI_INVOICE ON QA_INVOICE_LINE_ITEMS(INVOICE_ID);

-- ==========================
-- TABLE 7: INVOICE PAYMENTS
-- ==========================
CREATE TABLE QA_INVOICE_PAYMENTS (
    PAYMENT_ID       NUMBER         GENERATED ALWAYS AS IDENTITY,
    INVOICE_ID       VARCHAR2(50)   NOT NULL,
    AMOUNT           NUMBER(15,4)   NOT NULL,
    PAYMENT_DATE     VARCHAR2(20),
    PAYMENT_METHOD   VARCHAR2(100),
    REFERENCE_NUMBER VARCHAR2(255),
    CREATED_AT       TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_INV_PAYMENTS PRIMARY KEY (PAYMENT_ID),
    CONSTRAINT FK_PAY_INVOICE FOREIGN KEY (INVOICE_ID)
        REFERENCES QA_INVOICES(INVOICE_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_PAY_INVOICE ON QA_INVOICE_PAYMENTS(INVOICE_ID);

-- ==========================
-- SEQUENCE: Quote Auto-Number
-- ==========================
CREATE SEQUENCE QA_QUOTE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- ==========================
-- TABLE 8: QUOTES
-- ==========================
CREATE TABLE QA_QUOTES (
    QUOTE_ID           VARCHAR2(50)   NOT NULL,
    STATUS             VARCHAR2(20)   DEFAULT 'DRAFT',
    CREATED_BY         VARCHAR2(255),
    CUSTOMER_ID        VARCHAR2(50),
    CUSTOMER_NAME      VARCHAR2(500),
    QUOTE_DATE         VARCHAR2(20),
    EXPIRES_AT         VARCHAR2(50),
    INCOTERM           VARCHAR2(20),
    CURRENCY           VARCHAR2(10)   DEFAULT 'GHS',
    NOTES              VARCHAR2(4000),
    TERMS              VARCHAR2(4000),
    SUBTOTAL           NUMBER(15,4)   DEFAULT 0,
    SHIPPING_CHARGE    NUMBER(15,4)   DEFAULT 0,
    INSURANCE_CHARGE   NUMBER(15,4)   DEFAULT 0,
    ORDER_DISCOUNT     NUMBER(15,4)   DEFAULT 0,
    HANDLING_CHARGE    NUMBER(15,4)   DEFAULT 0,
    TAX                NUMBER(15,4)   DEFAULT 0,
    TOTAL              NUMBER(15,4)   DEFAULT 0,
    GROSS_MARGIN_PCT   NUMBER(10,4),
    AUDIT_COMPUTED_BY  VARCHAR2(100),
    AUDIT_COMPUTED_AT  TIMESTAMP,
    AUDIT_VALIDATED    NUMBER(1)      DEFAULT 0,
    CONVERTED_TO_INV   VARCHAR2(50),
    CONVERSION_DATE    TIMESTAMP,
    CREATED_AT         TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT         TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_QUOTES PRIMARY KEY (QUOTE_ID),
    CONSTRAINT FK_QT_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES QA_CUSTOMERS(CUSTOMER_ID)
);

CREATE INDEX IDX_QT_CUSTOMER  ON QA_QUOTES(CUSTOMER_ID);
CREATE INDEX IDX_QT_CREATED   ON QA_QUOTES(CREATED_BY);
CREATE INDEX IDX_QT_STATUS    ON QA_QUOTES(STATUS);

-- ==========================
-- TABLE 9: QUOTE LINE ITEMS
-- ==========================
CREATE TABLE QA_QUOTE_LINE_ITEMS (
    LINE_ID              NUMBER         GENERATED ALWAYS AS IDENTITY,
    QUOTE_ID             VARCHAR2(50)   NOT NULL,
    SKU                  VARCHAR2(100),
    DESCRIPTION          VARCHAR2(500),
    QUANTITY             NUMBER(10,2)   DEFAULT 1,
    UNIT_COST            NUMBER(15,4)   DEFAULT 0,
    FREIGHT_BREAKDOWN    NUMBER(15,4)   DEFAULT 0,
    DUTY_BREAKDOWN       NUMBER(15,4)   DEFAULT 0,
    INSURANCE_BREAKDOWN  NUMBER(15,4)   DEFAULT 0,
    PACKAGING_BREAKDOWN  NUMBER(15,4)   DEFAULT 0,
    OTHER_BREAKDOWN      NUMBER(15,4)   DEFAULT 0,
    UNIT_LANDED_COST     NUMBER(15,4)   DEFAULT 0,
    MARKUP_PERCENT       NUMBER(10,4)   DEFAULT 0,
    PRICING_MODE         VARCHAR2(20)   DEFAULT 'markup',
    UNIT_PRICE           NUMBER(15,4)   DEFAULT 0,
    LINE_TOTAL           NUMBER(15,4)   DEFAULT 0,
    SORT_ORDER           NUMBER(5,0)    DEFAULT 0,
    CONSTRAINT PK_QT_LINE_ITEMS PRIMARY KEY (LINE_ID),
    CONSTRAINT FK_QLI_QUOTE FOREIGN KEY (QUOTE_ID)
        REFERENCES QA_QUOTES(QUOTE_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_QLI_QUOTE ON QA_QUOTE_LINE_ITEMS(QUOTE_ID);

-- ==========================
-- TABLE 10: AUDIT LOGS
-- ==========================
CREATE TABLE QA_AUDIT_LOGS (
    LOG_ID     NUMBER         GENERATED ALWAYS AS IDENTITY,
    LOG_TIME   TIMESTAMP      DEFAULT SYSTIMESTAMP,
    USER_ID    VARCHAR2(255),
    ACTION     VARCHAR2(255),
    DETAILS    VARCHAR2(4000),
    CATEGORY   VARCHAR2(50),
    EXTRA_DATA CLOB,
    CONSTRAINT PK_AUDIT_LOGS PRIMARY KEY (LOG_ID)
);

CREATE INDEX IDX_AL_USER     ON QA_AUDIT_LOGS(USER_ID);
CREATE INDEX IDX_AL_TIME     ON QA_AUDIT_LOGS(LOG_TIME);
CREATE INDEX IDX_AL_CATEGORY ON QA_AUDIT_LOGS(CATEGORY);

-- ==========================
-- TABLE 11: TAX SETTINGS
-- ==========================
CREATE TABLE QA_TAX_SETTINGS (
    TAX_ID     VARCHAR2(50)   NOT NULL,
    TAX_NAME   VARCHAR2(100)  NOT NULL,
    TAX_RATE   NUMBER(10,4)   DEFAULT 0,
    IS_ENABLED NUMBER(1)      DEFAULT 1,
    APPLIED_ON VARCHAR2(20)   DEFAULT 'levyTotal',
    SORT_ORDER NUMBER(5,0)    DEFAULT 0,
    UPDATED_AT TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_TAX_SETTINGS PRIMARY KEY (TAX_ID),
    CONSTRAINT CHK_TAX_ENABLED CHECK (IS_ENABLED IN (0,1)),
    CONSTRAINT CHK_TAX_ON CHECK (APPLIED_ON IN ('subtotal','levyTotal'))
);

-- Seed default Ghana taxes
INSERT INTO QA_TAX_SETTINGS VALUES ('nhil',   'NHIL',           2.5,  1, 'subtotal',  1, SYSTIMESTAMP);
INSERT INTO QA_TAX_SETTINGS VALUES ('getfund','GETFund',         2.5,  1, 'subtotal',  2, SYSTIMESTAMP);
INSERT INTO QA_TAX_SETTINGS VALUES ('covid19','COVID-19 Levy',   1.0,  1, 'levyTotal', 3, SYSTIMESTAMP);
INSERT INTO QA_TAX_SETTINGS VALUES ('vat',   'VAT Standard',    15.0, 1, 'levyTotal', 4, SYSTIMESTAMP);

-- ==========================
-- TABLE 12: EXCHANGE RATES
-- ==========================
CREATE TABLE QA_EXCHANGE_RATES (
    RATE_ID    VARCHAR2(50)   NOT NULL,
    RATE_MONTH VARCHAR2(7)    NOT NULL,
    USD_TO_GHS NUMBER(15,6)   NOT NULL,
    CREATED_AT TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CREATED_BY VARCHAR2(255),
    UPDATED_AT TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_BY VARCHAR2(255),
    CONSTRAINT PK_EXCHANGE_RATES PRIMARY KEY (RATE_ID),
    CONSTRAINT UQ_RATE_MONTH UNIQUE (RATE_MONTH)
);

-- ==========================
-- TABLE 13: SIGNATURES
-- ==========================
CREATE TABLE QA_SIGNATURES (
    SIG_ID          VARCHAR2(50)   NOT NULL,
    CONTROLLER_NAME VARCHAR2(255)  NOT NULL,
    SUBSIDIARY      VARCHAR2(50),
    SIGNATURE_URL   CLOB,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CREATED_BY      VARCHAR2(255),
    CONSTRAINT PK_SIGNATURES PRIMARY KEY (SIG_ID)
);

-- ==========================
-- TABLE 14: INVOICE COUNTER
-- ==========================
CREATE TABLE QA_INVOICE_COUNTER (
    COUNTER_KEY VARCHAR2(20)   NOT NULL,
    COUNTER_VAL NUMBER(10,0)   DEFAULT 0,
    CONSTRAINT PK_INVOICE_COUNTER PRIMARY KEY (COUNTER_KEY)
);

INSERT INTO QA_INVOICE_COUNTER (COUNTER_KEY, COUNTER_VAL) VALUES ('main', 0);

-- ==========================
-- TABLE 15: COMPANY SETTINGS
-- ==========================
CREATE TABLE QA_COMPANY_SETTINGS (
    SETTING_KEY VARCHAR2(50)   NOT NULL,
    SETTING_VAL CLOB,
    CONSTRAINT PK_COMPANY_SETTINGS PRIMARY KEY (SETTING_KEY)
);

-- Seed default company data
INSERT INTO QA_COMPANY_SETTINGS (SETTING_KEY, SETTING_VAL) VALUES (
    'companyAddress',
    '{"poBox":"P.O. Box KN 785","city":"Accra, Ghana","tel":"+233 302 220 180","fax":"+233 302 220 180","email":"sales@margins-id.com"}'
);
INSERT INTO QA_COMPANY_SETTINGS (SETTING_KEY, SETTING_VAL) VALUES (
    'accountDetails',
    '{"accountName":"Margins ID Systems Applications Ltd.","bankers":"Fidelity Bank Limited","address":"Ridge Towers, Cruickshank Road, Ridge, Accra","accountNumbers":"1070033129318 - GHC"}'
);
INSERT INTO QA_COMPANY_SETTINGS (SETTING_KEY, SETTING_VAL) VALUES (
    'locationAddress',
    '{"companyName":"Margins ID Systems Applications Ltd.","unit":"Unit B607, Octagon","street":"Barnes Road, Accra Central"}'
);

-- ==========================
-- TABLE 16: PRICING SETTINGS
-- ==========================
CREATE TABLE QA_PRICING_SETTINGS (
    ID                     VARCHAR2(20)   NOT NULL,
    DEFAULT_MARKUP_PCT     NUMBER(10,4)   DEFAULT 32,
    DEFAULT_MARGIN_PCT     NUMBER(10,4)   DEFAULT 15,
    PRICING_MODE           VARCHAR2(20)   DEFAULT 'markup',
    ALLOCATION_METHOD      VARCHAR2(20)   DEFAULT 'weight',
    ROUNDING_DECIMALS      NUMBER(3,0)    DEFAULT 2,
    DEFAULT_INCOTERM       VARCHAR2(20)   DEFAULT 'FOB',
    DEFAULT_CURRENCY       VARCHAR2(10)   DEFAULT 'GHS',
    DEFAULT_QUOTE_EXPIRY   NUMBER(5,0)    DEFAULT 30,
    MIN_MARGIN_PCT         NUMBER(10,4)   DEFAULT 15,
    MAX_DISCOUNT_PCT       NUMBER(10,4)   DEFAULT 20,
    REQUIRE_APPROVAL_ABOVE NUMBER(15,4)   DEFAULT 10000,
    DEFAULT_TAX_RATE       NUMBER(10,6)   DEFAULT 0.12,
    UPDATED_AT             TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_PRICING PRIMARY KEY (ID)
);

INSERT INTO QA_PRICING_SETTINGS VALUES (
    'pricing', 32, 15, 'markup', 'weight', 2, 'FOB', 'GHS', 30, 15, 20, 10000, 0.12, SYSTIMESTAMP
);

-- ==========================
-- TABLE 17: REVENUE TARGETS
-- ==========================
CREATE TABLE QA_REVENUE_TARGETS (
    TARGET_ID     NUMBER         GENERATED ALWAYS AS IDENTITY,
    TARGET_YEAR   NUMBER(4,0)    NOT NULL,
    TARGET_MONTH  VARCHAR2(2)    NOT NULL,
    TARGET_AMOUNT NUMBER(15,4)   DEFAULT 0,
    ANNUAL_TARGET NUMBER(15,4),
    UPDATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_REVENUE_TARGETS PRIMARY KEY (TARGET_ID),
    CONSTRAINT UQ_YEAR_MONTH UNIQUE (TARGET_YEAR, TARGET_MONTH)
);

-- ============================================================
COMMIT;

-- Verification query
SELECT TABLE_NAME, NUM_ROWS
FROM USER_TABLES
ORDER BY TABLE_NAME;
-- Expected: 17 tables returned
