-- ============================================================
-- PROCUREMENT MODULE ROLLBACK (reverses schema_procurement.sql)
-- Run this in SQL Developer connected as QUOTEAPP user.
-- ============================================================

-- Drop in reverse dependency order
DROP TABLE QA_RFQ_RESPONSES      CASCADE CONSTRAINTS;
DROP TABLE QA_RFQ_VENDORS        CASCADE CONSTRAINTS;
DROP TABLE QA_RFQ_LINE_ITEMS     CASCADE CONSTRAINTS;
DROP TABLE QA_RFQS               CASCADE CONSTRAINTS;
DROP TABLE QA_PURCHASE_REQUISITIONS CASCADE CONSTRAINTS;
DROP TABLE QA_VENDORS            CASCADE CONSTRAINTS;
DROP TABLE QA_PROCUREMENT_EVENTS CASCADE CONSTRAINTS;
DROP TABLE QA_PROCUREMENT_SETTINGS CASCADE CONSTRAINTS;

DROP SEQUENCE QA_PR_SEQ;
DROP SEQUENCE QA_RFQ_SEQ;

-- Revert additive columns on QA_INVOICES
ALTER TABLE QA_INVOICES DROP CONSTRAINT CHK_INV_SOURCING;
ALTER TABLE QA_INVOICES DROP (SOURCING_STATUS, PR_COUNT);

-- Restore original USER_ROLE constraint
ALTER TABLE QA_USERS DROP CONSTRAINT CHK_USERS_ROLE;
ALTER TABLE QA_USERS ADD CONSTRAINT CHK_USERS_ROLE
    CHECK (USER_ROLE IN ('sales','controller'));

COMMIT;

-- Verification: expect zero rows
SELECT TABLE_NAME FROM USER_TABLES
WHERE TABLE_NAME IN (
    'QA_VENDORS','QA_PURCHASE_REQUISITIONS','QA_RFQS','QA_RFQ_LINE_ITEMS',
    'QA_RFQ_VENDORS','QA_RFQ_RESPONSES','QA_PROCUREMENT_EVENTS','QA_PROCUREMENT_SETTINGS'
);
